### PR TITLE
Update VatCalculator.php

### PR DESCRIPTION
**Pull request by DonCamillo11**
Added a method to return all tax rates for a given country code

### CODE REVIEW

**Comment by driesvints** [comment]
Thanks @DonCamillo11, I appreciate the PR! Could you also add it to the docs in the readme?

**Comment by DonCamillo11** [comment]
OK @driesvints, please check the readme file.

**Comment by driesvints** [comment]
Released

**Comment by DonCamillo11** [comment]
thanks

**Pull request merged**
